done
MorozDS/nodejs-homework-rest-api pull request #2
Opened 2023-02-10 18:23 UTC by MorozDS

Перевірте будь-ласка

2023-02-10 19:26 UTC, KhYulian requested changes
Потрібна правка

2023-02-10 19:26 UTC, KhYulian commented on routes/api/contacts.js
> +contactsRouter.patch("/:id/favorite", tryCatchWrapper(updateStatusContact));
Використайте validateBody

2023-02-10 19:26 UTC, KhYulian commented on controllers/contacts.controllers.js
> +  }
Ця перевірка непотрібна в контроллері, використовуйте validateBody

2023-02-12 20:14 UTC, MorozDS commented on controllers/contacts.controllers.js
> +  }
Виправив

2023-02-13 06:55 UTC, KhYulian approved these changes
Чудова робота :)

2023-02-13 06:55 UTC, merged